name: PlayOK Selenium Bot

on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 每6小时运行一次（UTC时间）
    - cron: '0 */6 * * *'

jobs:
  selenium-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
    - name: Install Chrome
      run: |
        sudo apt-get install -y google-chrome-stable
        echo "Chrome version:"
        google-chrome --version
        
    - name: Install ChromeDriver
      run: |
        # 获取Chrome版本
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | cut -d'.' -f1-3)
        echo "Chrome version: $CHROME_VERSION"
        
        # 下载对应版本的ChromeDriver
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        echo "ChromeDriver version:"
        chromedriver --version
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests
        
    - name: Run Selenium Bot
      env:
        PLAYOK_USERNAME: ${{ secrets.PLAYOK_USERNAME }}
        PLAYOK_PASSWORD: ${{ secrets.PLAYOK_PASSWORD }}
      run: |
        python bot.py
