name: PlayOK Selenium Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  selenium-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        echo "Chrome version:"
        google-chrome --version
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests webdriver-manager
        
    - name: Run Selenium Bot
      env:
        PLAYOK_USERNAME: ${{ secrets.PLAYOK_USERNAME }}
        PLAYOK_PASSWORD: ${{ secrets.PLAYOK_PASSWORD }}
      run: |
        python bot.py
